title: Garden Of Garbage
author: Shiyu Dong
email: shiyudong@bnu.edu.cn
description: >-
  a garden to log the garbage of my life
baseurl: ""
url: ""
github_username: shiyuDong-bnu

show_excerpts: true

header_pages:
  - about.markdown

minima:
  date_format: "%Y-%m-%d"

theme: minima
plugins:
  - jekyll-feed
